-- =====================================================
-- SHIFHA SUPABASE SQL - COMPLETE VERSION (TÜM TABLOLAR)
-- =====================================================

-- NOT: Bu dosya tüm tabloları güvenli bir şekilde oluşturur
-- Mevcut tablolar zaten varsa bu komutlar hata vermez

-- =====================================================
-- 0. TEMİZLİK İŞLEMLERİ (DUPLICATE TABLOLAR)
-- =====================================================

-- Eğer "Patient" (PascalCase) tablosu varsa sil (yanlış isimlendirme)
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'Patient') THEN
        DROP TABLE public."Patient" CASCADE;
        RAISE NOTICE 'Patient (PascalCase) tablosu silindi - yanlış isimlendirme';
    END IF;
END $$;

-- Eğer "BloodTestAnalysis" (PascalCase) tablosu varsa sil (yanlış isimlendirme)
DO $$ 
BEGIN
    IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'BloodTestAnalysis') THEN
        DROP TABLE public."BloodTestAnalysis" CASCADE;
        RAISE NOTICE 'BloodTestAnalysis (PascalCase) tablosu silindi - yanlış isimlendirme';
    END IF;
END $$;

-- =====================================================
-- 1. PROFILES TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Eğer profiles tablosu yoksa oluştur (varsa hata vermez)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'profiles') THEN
        CREATE TABLE public.profiles (
            id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
            name TEXT,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Enable RLS for profiles
        ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
        
        -- Policy to allow users to manage their own profile
        CREATE POLICY "Users can manage their own profile" ON public.profiles
        FOR ALL TO authenticated 
        USING (auth.uid() = id)
        WITH CHECK (auth.uid() = id);
        
        RAISE NOTICE 'Profiles tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Profiles tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 2. PATIENTS TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Patients tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'patients') THEN
        CREATE TABLE public.patients (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
            tc_kimlik_no CHARACTER VARYING NOT NULL DEFAULT ''::CHARACTER VARYING,
            ad_soyad CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            dogum_tarihi CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            yas INTEGER NULL,
            cinsiyet CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            boy CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            vki CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            kan_grubu CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            medeni_durum CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            meslek CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            egitim_durumu CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            kronik_hastaliklar TEXT NULL DEFAULT ''::TEXT,
            ameliyatlar TEXT NULL DEFAULT ''::TEXT,
            allerjiler TEXT NULL DEFAULT ''::TEXT,
            aile_oykusu TEXT NULL DEFAULT ''::TEXT,
            enfeksiyonlar TEXT NULL DEFAULT ''::TEXT,
            ilac_duzenli TEXT NULL DEFAULT ''::TEXT,
            ilac_duzensiz TEXT NULL DEFAULT ''::TEXT,
            ilac_alternatif TEXT NULL DEFAULT ''::TEXT,
            hareket CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            uyku CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            sigara_alkol CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            beslenme CHARACTER VARYING NULL,
            psikoloji CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            uyku_bozuklugu CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            sosyal_destek CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
            kilo CHARACTER VARYING NULL,
            patient_data JSONB NULL,
            CONSTRAINT patients_pkey PRIMARY KEY (tc_kimlik_no)
        ) TABLESPACE pg_default;
        
        RAISE NOTICE 'Patients tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Patients tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 3. CITIES TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Cities tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'cities') THEN
        CREATE TABLE public.cities (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name TEXT NOT NULL UNIQUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Enable RLS
        ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
        
        -- Policy to allow all users to view cities
        CREATE POLICY "Cities are viewable by all" ON public.cities
        FOR SELECT TO authenticated USING (true);
        
        RAISE NOTICE 'Cities tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Cities tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 4. DISTRICTS TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Districts tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'districts') THEN
        CREATE TABLE public.districts (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            city_id BIGINT NOT NULL REFERENCES public.cities(id),
            name TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(city_id, name)
        );
        
        -- Create index for foreign key
        CREATE INDEX idx_districts_city_id ON public.districts(city_id);
        
        -- Enable RLS
        ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
        
        -- Policy to allow all users to view districts
        CREATE POLICY "Districts are viewable by all" ON public.districts
        FOR SELECT TO authenticated USING (true);
        
        RAISE NOTICE 'Districts tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Districts tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 5. HOSPITALS TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Hospitals tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'hospitals') THEN
        CREATE TABLE public.hospitals (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            district_id BIGINT NOT NULL REFERENCES public.districts(id),
            name TEXT NOT NULL,
            address TEXT,
            phone TEXT,
            email TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(district_id, name)
        );
        
        -- Create index for foreign key
        CREATE INDEX idx_hospitals_district_id ON public.hospitals(district_id);
        
        -- Enable RLS
        ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
        
        -- Policy to allow all users to view hospitals
        CREATE POLICY "Hospitals are viewable by all" ON public.hospitals
        FOR SELECT TO authenticated USING (true);
        
        RAISE NOTICE 'Hospitals tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Hospitals tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 6. DOCTOR_PROFILES TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Doctor_profiles tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'doctor_profiles') THEN
        CREATE TABLE public.doctor_profiles (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            hospital_id BIGINT NULL REFERENCES public.hospitals(id),
            tc_kimlik_no TEXT NOT NULL UNIQUE,
            full_name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            specialization TEXT,
            department TEXT,
            is_active BOOLEAN DEFAULT TRUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create indexes
        CREATE INDEX idx_doctor_profiles_user_id ON public.doctor_profiles(user_id);
        CREATE INDEX idx_doctor_profiles_hospital_id ON public.doctor_profiles(hospital_id);
        
        -- Enable RLS
        ALTER TABLE public.doctor_profiles ENABLE ROW LEVEL SECURITY;
        
        -- Policy for doctors to manage their own profile
        CREATE POLICY "Doctors can manage their own profile" ON public.doctor_profiles
        FOR ALL TO authenticated 
        USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id);
        
        -- Policy for admin to view all doctor profiles
        CREATE POLICY "Admins can view all doctor profiles" ON public.doctor_profiles
        FOR SELECT TO authenticated 
        USING ((SELECT auth.jwt() ->> 'role') = 'admin');
        
        RAISE NOTICE 'Doctor_profiles tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Doctor_profiles tablosu zaten mevcut';
        
        -- Mevcut tabloda hospital_id alanını opsiyonel yap
        IF EXISTS (
            SELECT FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'doctor_profiles' 
            AND column_name = 'hospital_id'
            AND is_nullable = 'NO'
        ) THEN
            ALTER TABLE public.doctor_profiles ALTER COLUMN hospital_id DROP NOT NULL;
            RAISE NOTICE 'Doctor_profiles.hospital_id alanı opsiyonel yapıldı';
        ELSE
            RAISE NOTICE 'Doctor_profiles.hospital_id alanı zaten opsiyonel';
        END IF;
    END IF;
END $$;

-- =====================================================
-- 7. PATIENT_PROFILES TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Patient_profiles tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'patient_profiles') THEN
        CREATE TABLE public.patient_profiles (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            tc_kimlik_no TEXT NOT NULL UNIQUE,
            full_name TEXT NOT NULL,
            email TEXT,
            phone TEXT,
            birth_date DATE,
            gender TEXT,
            address TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create index for user_id
        CREATE INDEX idx_patient_profiles_user_id ON public.patient_profiles(user_id);
        
        -- Enable RLS
        ALTER TABLE public.patient_profiles ENABLE ROW LEVEL SECURITY;
        
        -- Policy to allow users to view and edit only their own profile
        CREATE POLICY "Users can manage their own profile" ON public.patient_profiles
        FOR ALL TO authenticated 
        USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id);
        
        RAISE NOTICE 'Patient_profiles tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Patient_profiles tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 8. APPOINTMENTS TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- Appointment_status enum kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM pg_type WHERE typname = 'appointment_status') THEN
        CREATE TYPE appointment_status AS ENUM ('pending', 'confirmed', 'cancelled', 'completed');
        RAISE NOTICE 'Appointment_status enum oluşturuldu';
    ELSE
        RAISE NOTICE 'Appointment_status enum zaten mevcut';
    END IF;
END $$;

-- Appointments tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'appointments') THEN
        CREATE TABLE public.appointments (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            patient_id BIGINT NOT NULL REFERENCES public.patient_profiles(id),
            doctor_id BIGINT NOT NULL REFERENCES public.doctor_profiles(id),
            hospital_id BIGINT NOT NULL REFERENCES public.hospitals(id),
            appointment_date DATE NOT NULL,
            appointment_time TIME NOT NULL,
            status appointment_status DEFAULT 'pending',
            notes TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(doctor_id, appointment_date, appointment_time)
        );
        
        -- Create indexes
        CREATE INDEX idx_appointments_patient_id ON public.appointments(patient_id);
        CREATE INDEX idx_appointments_doctor_id ON public.appointments(doctor_id);
        CREATE INDEX idx_appointments_hospital_id ON public.appointments(hospital_id);
        
        -- Enable RLS
        ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
        
        -- Policy for patients to view and manage their own appointments
        CREATE POLICY "Patients can manage their own appointments" ON public.appointments
        FOR ALL TO authenticated 
        USING (patient_id = (SELECT id FROM public.patient_profiles WHERE user_id = auth.uid()))
        WITH CHECK (patient_id = (SELECT id FROM public.patient_profiles WHERE user_id = auth.uid()));
        
        -- Policy for doctors to view their appointments
        CREATE POLICY "Doctors can view their appointments" ON public.appointments
        FOR SELECT TO authenticated 
        USING (doctor_id = (SELECT id FROM public.doctor_profiles WHERE user_id = auth.uid()));
        
        -- Policy for admins to manage all appointments
        CREATE POLICY "Admins can manage all appointments" ON public.appointments
        FOR ALL TO authenticated 
        USING ((SELECT auth.jwt() ->> 'role') = 'admin')
        WITH CHECK ((SELECT auth.jwt() ->> 'role') = 'admin');
        
        RAISE NOTICE 'Appointments tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'Appointments tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 9. BLOOD_TEST_ANALYSIS TABLOSU KONTROLÜ VE GÜNCELLEME
-- =====================================================

-- BloodTestAnalysis tablosu kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'blood_test_analysis') THEN
        CREATE TABLE public.blood_test_analysis (
            id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
            patient_tc_kimlik_no CHARACTER VARYING NOT NULL REFERENCES public.patients(tc_kimlik_no) ON DELETE CASCADE,
            results TEXT,
            gemini_response TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Create index for blood test analysis
        CREATE INDEX idx_blood_test_analysis_user_id ON public.blood_test_analysis(user_id);
        CREATE INDEX idx_blood_test_analysis_patient_tc ON public.blood_test_analysis(patient_tc_kimlik_no);
        
        -- Enable RLS
        ALTER TABLE public.blood_test_analysis ENABLE ROW LEVEL SECURITY;
        
        -- Policy for users to manage their own blood test analysis
        CREATE POLICY "Users can manage their own blood test analysis" ON public.blood_test_analysis
        FOR ALL TO authenticated 
        USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id);
        
        RAISE NOTICE 'BloodTestAnalysis tablosu oluşturuldu';
    ELSE
        RAISE NOTICE 'BloodTestAnalysis tablosu zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 10. MEVCUT TABLOLARIN RLS KONTROLÜ
-- =====================================================

-- Patients tablosu RLS kontrolü
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_policies 
        WHERE tablename = 'patients' 
        AND schemaname = 'public'
    ) THEN
        ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
        
        -- Policy for patients (basit bir policy)
        CREATE POLICY "Patients are viewable by authenticated users" ON public.patients
        FOR SELECT TO authenticated USING (true);
        
        CREATE POLICY "Patients can be managed by authenticated users" ON public.patients
        FOR ALL TO authenticated USING (true) WITH CHECK (true);
        
        RAISE NOTICE 'Patients tablosu için RLS policy eklendi';
    ELSE
        RAISE NOTICE 'Patients tablosu için RLS policy zaten mevcut';
    END IF;
END $$;

-- =====================================================
-- 11. TEST VERİLERİ (İSTEĞE BAĞLI)
-- =====================================================

-- Test için örnek şehir ekle (eğer yoksa)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT FROM public.cities WHERE name = 'İstanbul') THEN
        INSERT INTO public.cities (name) VALUES ('İstanbul');
        RAISE NOTICE 'Test şehri eklendi: İstanbul';
    END IF;
    
    IF NOT EXISTS (SELECT FROM public.cities WHERE name = 'Ankara') THEN
        INSERT INTO public.cities (name) VALUES ('Ankara');
        RAISE NOTICE 'Test şehri eklendi: Ankara';
    END IF;
    
    IF NOT EXISTS (SELECT FROM public.cities WHERE name = 'İzmir') THEN
        INSERT INTO public.cities (name) VALUES ('İzmir');
        RAISE NOTICE 'Test şehri eklendi: İzmir';
    END IF;
END $$;

-- =====================================================
-- 12. VERİTABANI DURUMU KONTROLÜ
-- =====================================================

-- Mevcut tabloları listele
SELECT 
    table_name,
    CASE 
        WHEN table_name IN ('profiles', 'doctor_profiles', 'patients', 'blood_test_analysis', 'cities', 'districts', 'hospitals', 'patient_profiles', 'appointments') 
        THEN '✅ Gerekli Tablo'
        ELSE '📋 Diğer Tablo'
    END as status
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- =====================================================
-- 13. KAYIT SİSTEMİ İÇİN GEREKLİ KONTROLLER
-- =====================================================

-- Profiles tablosu yapısını kontrol et
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'profiles'
ORDER BY ordinal_position;

-- Doctor_profiles tablosu yapısını kontrol et
SELECT 
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'doctor_profiles'
ORDER BY ordinal_position;

-- =====================================================
-- BAŞARI MESAJI
-- =====================================================

DO $$ 
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'SHIFHA VERİTABANI KURULUMU TAMAMLANDI!';
    RAISE NOTICE '========================================';
    RAISE NOTICE '✅ Duplicate tablolar temizlendi';
    RAISE NOTICE '✅ Profiles tablosu hazır';
    RAISE NOTICE '✅ Doctor_profiles tablosu hazır';
    RAISE NOTICE '✅ Patients tablosu hazır (snake_case)';
    RAISE NOTICE '✅ Cities tablosu hazır';
    RAISE NOTICE '✅ Districts tablosu hazır';
    RAISE NOTICE '✅ Hospitals tablosu hazır';
    RAISE NOTICE '✅ Patient_profiles tablosu hazır';
    RAISE NOTICE '✅ Appointments tablosu hazır';
    RAISE NOTICE '✅ BloodTestAnalysis tablosu hazır (snake_case)';
    RAISE NOTICE '✅ RLS policies aktif';
    RAISE NOTICE '✅ Kayıt sistemi için hazır';
    RAISE NOTICE '========================================';
END $$; 